---
# Source: https://github.com/geerlingguy/ansible-role-mysql/blob/master/.travis.yml

services: docker

env:
  - distro: debian9
    playbook: test.yml
    test_idempotence: false
  - distro: ubuntu1804
    playbook: test.yml
    test_idempotence: false

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh  https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/2dc8100bab92da745c7a7b38990df2a3546048d0/ansible-role-test.sh
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
