---
# Source: https://github.com/geerlingguy/ansible-role-mysql/blob/master/.travis.yml

services: docker

env:
  - distro: debian9
    playbook: test.yml
  - distro: ubuntu1804
    playbook: test.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/Phill93/9893096e9a26cedc3b6db5d4f7df5e7c/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
