---
- name: Install required packages
  apt:
    name: "{{ nextcloud_php_modules }}"
    state: present
    update-cache: yes
  notify: restart webserver

- name: Check if Installed
  stat: "path={{ nextcloud_install_dir}}/config/config.php"
  register: installed

- name: Creating Nextcloud directory
  file:
    path: "{{ nextcloud_install_dir }}"
    state: directory

- name: Creating Nextcloud data directory
  file:
    path: "{{ nextcloud_data_dir }}"
    state: directory

- name: Extracting Nextcloud archive "{{ nextcloud_download_url }}" to "{{ nextcloud_install_dir }}"
  unarchive:
    src: "{{ nextcloud_download_url }}"
    remote_src: yes
    dest: "{{ nextcloud_extract_dir }}"
  when: installed.stat.exists == False

- name: Setting file permissions
  file:
    path: "{{ nextcloud_install_dir }}"
    mode: 0640
    owner: "{{ nextcloud_http_user }}"
    group: "{{ nextcloud_http_group }}"
    recurse: yes

- name: Setting data folder file permissions
  file:
    path: "{{ nextcloud_data_dir }}"
    mode: 0640
    owner: "{{ nextcloud_http_user }}"
    group: "{{ nextcloud_http_group }}"
    recurse: yes

- name: Setting folder permissions
  file:
    path: "{{ nextcloud_install_dir }}"
    mode: 0755
    owner: "{{ nextcloud_http_user }}"
    group: "{{ nextcloud_http_group }}"
    state: directory
    recurse: yes

- name: Setting folder permissions
  file:
    path: "{{ nextcloud_install_dir }}/{{ item }}"
    mode: 0750
    owner: "{{ nextcloud_http_user}}"
    group: "{{ nextcloud_http_group}}"
    recurse: yes
    state: directory
  with_items: "{{ nextcloud_folders }}"

- name: Setting data folder permissions
  file:
    path: "{{ nextcloud_data_dir }}"
    mode: 0750
    owner: "{{ nextcloud_http_user }}"
    group: "{{ nextcloud_http_group }}"
    recurse: yes
    state: directory

- name: Setting .htaccess permissions
  file:
    path: "{{ nextcloud_install_dir }}/.htaccess"
    mode: 0644
    owner: "{{ nextcloud_http_user }}"
    group: "{{ nextcloud_http_group }}"

- name: Setting data folder .htaccess permissions if exist
  file:
    path: "{{ nextcloud_data_dir }}/.htaccess"
    mode: 0644
    owner: "{{ nextcloud_http_user }}"
    group: "{{ nextcloud_http_group }}"
  ignore_errors: yes

- name: Make occ executable
  file:
    path: "{{ nextcloud_install_dir }}/occ"
    mode: 0751
    owner: "{{ nextcloud_http_user }}"
    group: "{{ nextcloud_http_group }}"

- name: Use occ to install Nextcloud
  shell: "{{ nextcloud_install_cmd }}"
  become: true
  become_user: "{{ nextcloud_http_user }}"
  when: installed.stat.exists == False

- name: Check if Installed
  stat: "path={{ nextcloud_install_dir}}/config/config.php"
  register: installed

