---
  - name: Install required packages
    apt:
      name: "{{ item }}"
      state: present
      update-cache: yes
    with_items:
      - "{{ nextcloud_php_modules }}"
      - bzip2
      - sudo
      - git
    notify: restart webserver

  - name: Check if Installed
    stat: path={{ nextcloud_install_dir}}/config/config.php
    register: installed

  - name: Creating Nextcloud directory
    file:
      path: "{{ nextcloud_install_dir }}"
      state: directory

  - name: Creating Nextcloud data directory
    file:
      path: "{{ nextcloud_data_dir }}"
      state: directory
    when: nextcloud_data_dir_storage_location is not defined

  - name: Create directory nextcloud_data_dir_storage_location
    file:
      path: "{{ nextcloud_data_dir_storage_location }}"
      state: directory
      mode: 0755
      recurse: yes
    when: nextcloud_data_dir_storage_location is defined

  - name: Create symbolic link for data directory
    file:
      src: "{{ nextcloud_data_dir_storage_location }}"
      dest: "{{ nextcloud_data_dir }}"
      owner: "{{ nextcloud_http_user }}"
      group: "{{ nextcloud_http_group }}"
      state: link
      mode: 0750
      owner: "{{ nextcloud_http_user }}"
      group: "{{ nextcloud_http_group }}"
    when: nextcloud_data_dir_storage_location is defined

  - name: Extracting Nextcloud archive ("{{ nextcloud_download_url }}") to "{{ nextcloud_install_dir }}"
    unarchive:
      src: "{{ nextcloud_download_url }}"
      remote_src: yes
      dest: "{{ nextcloud_extract_dir }}"
    when: installed.stat.exists == False

  - name: Setting file permissions
    file:
      path: "{{ nextcloud_install_dir }}"
      mode: 0640
      owner: "{{ nextcloud_http_user }}"
      group: "{{ nextcloud_http_group }}"
      recurse: yes

  - name: Setting data folder file permissions
    file:
      path: "{{ nextcloud_data_dir }}/"
      mode: 0640
      owner: "{{ nextcloud_http_user }}"
      group: "{{ nextcloud_http_group }}"
      recurse: yes

  - name: Setting folder permissions
    file:
      path: "{{ nextcloud_install_dir }}"
      mode: 0755
      owner: "{{ nextcloud_http_user }}"
      group: "{{ nextcloud_http_group }}"
      state: directory
      recurse: yes

  - name: Setting folder permissions
    file:
      path: "{{ nextcloud_install_dir }}/{{ item }}"
      mode: 0750
      owner: "{{ nextcloud_http_user}}"
      group: "{{ nextcloud_http_group}}"
      recurse: yes
      state: directory
    with_items: "{{ nextcloud_folders }}"

  - name: Setting data folder permissions
    file:
      path: "{{ nextcloud_data_dir }}"
      mode: 0750
      owner: "{{ nextcloud_http_user }}"
      group: "{{ nextcloud_http_group }}"
      recurse: yes
      state: directory

  - name: Setting .htaccess permissions
    file:
      path: "{{ nextcloud_install_dir }}/.htaccess"
      mode: 0644
      owner: "root"
      group: "{{ nextcloud_http_group }}"

  - name: Setting data folder .htaccess permissions if exist
    file:
      path: "{{ nextcloud_data_dir }}/.htaccess"
      mode: 0644
      owner: "root"
      group: "{{ nextcloud_http_group }}"
    ignore_errors: yes

  - name: Make occ executable
    file:
      path: "{{ nextcloud_install_dir }}/occ"
      mode: 0751
      owner: "{{ nextcloud_http_user }}"
      group: "{{ nextcloud_http_group }}"

  - name: Use occ to install Nextcloud
    shell: "{{ nextcloud_install_cmd }}"
    become: true
    when: installed.stat.exists == False

  - name: Check if Installed
    stat: path={{ nextcloud_install_dir}}/config/config.php
    register: installed

  - name: Install additional apps
    git:
      repo: "{{ item.repo }}"
      dest: "{{ nextcloud_install_dir }}/apps/{{ item.name }}"
      update: no
      version: "{{ item.version }}"
    with_items: "{{ nextcloud_additional_apps }}"
