---
- name: Install Cronjob
  cron:
    name: "Nextcloud Cronjob"
    minute: "*/15"
    user: "{{ nextcloud_http_user }}"
    job: "{{ nextcloud_cron_cmd}}"
    cron_file: "nextcloud"
  when: nextcloud_cron == True

- name: Set Cron method to Crontab
  shell: "{{ nextcloud_cron_en_cmd }}"
  become: true
  become_user: "{{ nextcloud_http_user }}"
  when: nextcloud_cron == True

