---
    - name: Install Cronjob
      cron:
        name: "Nextcloud Cronjob"
        minute: "*/15"
        user: "{{ nextcloud_http_user }}"
        job: "{{ nextcloud_cron_cmd}}"
        cron_file: "nextcloud"
      when: nextcloud_cron == True

    - name: Set Cron method to Crontab
      shell: "{{ nextcloud_cron_en_cmd }}"
      become: true
      when: nextcloud_cron == True

    - name: Configure custom cron jobs
      cron:
        name: "{{ item.name }}"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour }}"
        month: "{{ item.month }}"
        day: "{{ item.day }}"
        job: "{{ item.job }}"
        user: "{{ item.user }}"
      with_items:
        - "{{ nextcloud_custom_cron_jobs }}"
