---

- name: Create sekelton directory
  file:
    path: "{{ nextcloud_skeletondirectory }}"
    state: directory
  when: nextcloud_skeletondirectory is defined

- name: Configuring skeletondirectory in nextcloud/config/config.php
  shell: "{{ nextcloud_set_skeletondirectory_cmd }}"
  become: true
  when: nextcloud_skeletondirectory is defined

- name: Link user manual to skeleton
  file:
    src: "{{ nextcloud_extract_dir }}/nextcloud/core/skeleton/Nextcloud Manual.pdf"
    dest: "{{ nextcloud_skeletondirectory }}/Nextcloud Manual.pdf"
    state: link
  when: nextcloud_skeletondirectory_link_user_manual
  notify: restart webserver

  
- name: Set Trusted Proxies
  shell: "{{ nextcloud_set_trusted_proxies_cmd }}"
  become: true
  with_indexed_items: "{{ nextcloud_trusted_domains }}"
  when: nextcloud_trusted_proxies is defined
